#!/usr/bin/env node
/**
 * Safe-Bifrost MCP Server
 *
 * A secure bridge between ChatGPT (planning) and local AI coding agents
 * (Codex, OpenCode, etc.) for task execution with full result feedback.
 *
 * Run: node dist/index.js
 * Or via MCP config pointing to dist/index.js
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

import { loadConfig } from "./config.js";
import { savePlan } from "./tools/savePlan.js";
import { getPlan } from "./tools/getPlan.js";
import { createTask } from "./tools/createTask.js";
import { getTaskStatus } from "./tools/getTaskStatus.js";
import { getResult, getDiff, getTestLog } from "./tools/taskOutputs.js";
import { listWorkspace } from "./tools/listWorkspace.js";
import { readWorkspaceFile } from "./tools/readWorkspaceFile.js";

// ── Bootstrap ─────────────────────────────────────────────────────

const configPath = process.env.SAFE_BIFROST_CONFIG || undefined;
const config = loadConfig(configPath);

console.error(`[safe-bifrost] Workspace: ${config.workspaceRoot}`);
console.error(`[safe-bifrost] Plans:     ${config.plansDir}`);
console.error(`[safe-bifrost] Tasks:     ${config.tasksDir}`);

const server = new Server(
  { name: "safe-bifrost", version: "0.1.0" },
  { capabilities: { tools: {} } }
);

// ── Tool definitions ──────────────────────────────────────────────

interface ToolDef {
  name: string;
  description: string;
  inputSchema: {
    type: "object";
    properties: Record<string, unknown>;
    required?: string[];
  };
}

const TOOLS: ToolDef[] = [
  {
    name: "save_plan",
    description:
      "Save an execution plan — ChatGPT writes the plan, Safe-Bifrost stores it for local agent execution.",
    inputSchema: {
      type: "object",
      properties: {
        title: { type: "string", description: "Plan title" },
        content: { type: "string", description: "Plan content in Markdown" },
      },
      required: ["title", "content"],
    },
  },
  {
    name: "get_plan",
    description: "Read a saved plan by its plan_id.",
    inputSchema: {
      type: "object",
      properties: {
        plan_id: { type: "string", description: "Plan ID returned by save_plan" },
      },
      required: ["plan_id"],
    },
  },
  {
    name: "create_task",
    description:
      "Create a task from a plan. Links a plan to a local agent for execution.",
    inputSchema: {
      type: "object",
      properties: {
        plan_id: { type: "string", description: "Plan ID from save_plan" },
        agent: {
          type: "string",
          description: 'Agent name: "codex" or "opencode"',
        },
        repo_path: {
          type: "string",
          description: "Optional repo path (defaults to workspace root)",
        },
        test_command: {
          type: "string",
          description: "Optional test command from the allowlist",
        },
      },
      required: ["plan_id", "agent"],
    },
  },
  {
    name: "get_task_status",
    description: "Check the status of a task: pending, running, done, or failed.",
    inputSchema: {
      type: "object",
      properties: {
        task_id: { type: "string", description: "Task ID from create_task" },
      },
      required: ["task_id"],
    },
  },
  {
    name: "get_result",
    description: "Read the execution result (result.md) for a completed task.",
    inputSchema: {
      type: "object",
      properties: {
        task_id: { type: "string", description: "Task ID" },
      },
      required: ["task_id"],
    },
  },
  {
    name: "get_diff",
    description: "Read the git diff generated by a task execution.",
    inputSchema: {
      type: "object",
      properties: {
        task_id: { type: "string", description: "Task ID" },
      },
      required: ["task_id"],
    },
  },
  {
    name: "get_test_log",
    description: "Read the test log from a task execution.",
    inputSchema: {
      type: "object",
      properties: {
        task_id: { type: "string", description: "Task ID" },
      },
      required: ["task_id"],
    },
  },
  {
    name: "list_workspace",
    description:
      "List files and directories within the workspace (sensitive files excluded).",
    inputSchema: {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: "Optional relative path within workspace (default: root)",
        },
      },
    },
  },
  {
    name: "read_workspace_file",
    description:
      "Read a file within the workspace. Sensitive files (secrets, keys, tokens) are blocked.",
    inputSchema: {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: "Relative path to a file inside the workspace",
        },
      },
      required: ["path"],
    },
  },
];

// ── Request handlers ──────────────────────────────────────────────

server.setRequestHandler(ListToolsRequestSchema, async () => {
  return { tools: TOOLS };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    switch (name) {
      case "save_plan": {
        const result = savePlan({
          title: String(args?.title ?? ""),
          content: String(args?.content ?? ""),
        });
        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
        };
      }

      case "get_plan": {
        const result = getPlan({
          plan_id: String(args?.plan_id ?? ""),
        });
        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
        };
      }

      case "create_task": {
        const result = createTask({
          plan_id: String(args?.plan_id ?? ""),
          agent: String(args?.agent ?? ""),
          repo_path: args?.repo_path ? String(args.repo_path) : undefined,
          test_command: args?.test_command
            ? String(args.test_command)
            : undefined,
        });
        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
        };
      }

      case "get_task_status": {
        const taskId = String(args?.task_id ?? "");
        const result = getTaskStatus(taskId);
        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
        };
      }

      case "get_result": {
        const taskId = String(args?.task_id ?? "");
        const result = getResult(taskId);
        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
        };
      }

      case "get_diff": {
        const taskId = String(args?.task_id ?? "");
        const result = getDiff(taskId);
        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
        };
      }

      case "get_test_log": {
        const taskId = String(args?.task_id ?? "");
        const result = getTestLog(taskId);
        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
        };
      }

      case "list_workspace": {
        const result = listWorkspace(
          args?.path ? String(args.path) : undefined
        );
        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
        };
      }

      case "read_workspace_file": {
        const result = readWorkspaceFile(String(args?.path ?? ""));
        return {
          content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
        };
      }

      default:
        throw new Error(`Unknown tool: ${name}`);
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      content: [{ type: "text", text: JSON.stringify({ error: message }) }],
      isError: true,
    };
  }
});

// ── Start ─────────────────────────────────────────────────────────

const transport = new StdioServerTransport();
server.connect(transport).catch((err) => {
  console.error("[safe-bifrost] Fatal:", err);
  process.exit(1);
});

console.error("[safe-bifrost] MCP server ready on stdio");
